apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          args:
            - --provider=google
            - --client-id=$(GOOGLE_CLIENT_ID)
            - --client-secret=$(GOOGLE_CLIENT_SECRET)
            - --cookie-secret=$(COOKIE_SECRET)
            - --cookie-secure=true
            - --email-domain=mcarcoba.com
            - --redirect-url=https://mcarcoba.com/oauth2/callback
            - --upstream=static://200
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oidc-secret
                  key: client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oidc-secret
                  key: client-secret
            - name: COOKIE_SECRET
              value: <base64-encoded-random-secret>
          ports:
            - name: http
              containerPort: 4180
