apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mtls-auth
  namespace: traefik
spec:
  tls:
    clientAuth:
      caCertificates:
        - /certs/ca.crt
      clientAuthType: RequireAndVerifyClientCert
