apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: traefik
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.0.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: traefik
  interval: 1m
  values:
    replicaCount: 1
    extraEnv:
      - name: OAUTH2_PROXY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: google-oidc-secret
            key: client-id
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: google-oidc-secret
            key: client-secret
    config:
      cookieDomain: mcarcoba.com
      cookieSecret: 2kz_tV5L9t9mRVo5Qd62NvgjGVqH86Ie0U5k7Z6R_aM=
      cookieSecure: true
      provider: google
      redirectURL: https://auth.mcarcoba.com/oauth2/callback
      scopes:
        - email
      emailDomains:
        - mcarcoba.com
      upstreams:
        - file://dev/null
