apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickle-rick-investments
  labels:
    app: pickle-rick-investments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickle-rick-investments
  template:
    metadata:
      labels:
        app: pickle-rick-investments
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
        - name: pickle-rick-investments
          image: drizzt92/pickle-rick-investments:0.0.2
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickle-rick-investments-dev
  labels:
    app: pickle-rick-investments-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickle-rick-investments-dev
  template:
    metadata:
      labels:
        app: pickle-rick-investments-dev
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
        - name: pickle-rick-investments
          image: drizzt92/pickle-rick-investments:0.0.4
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: pickle-rick-investments
                  key: ENVIRONMENT
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: pickle-rick-investments
                  key: HTTP_PORT
            - name: GCP_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: pickle-rick-investments
                  key: GCP_BUCKET_NAME
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: pickle-rick-investments
                  key: GCP_PROJECT_ID
            - name: PATH_DB
              valueFrom:
                configMapKeyRef:
                  name: pickle-rick-investments
                  key: PATH_DB
            - name: ALPACA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: pickle-rick-investments
                  key: ALPACA_ENDPOINT
            - name: TELEGRAM_USERS
              valueFrom:
                configMapKeyRef:
                  name: pickle-rick-investments
                  key: TELEGRAM_USERS
            - name: ALPACA_KEY
              valueFrom:
                secretKeyRef:
                  name: pickle-rick-investments-conf
                  key: ALPACA_KEY
            - name: ALPACA_SECRET
              valueFrom:
                secretKeyRef:
                  name: pickle-rick-investments-conf
                  key: ALPACA_SECRET
            - name: TELEGRAM_BOT
              value: "7610149438:AAGWnNGNFyn4gbLDRZVWzsAsbVehhtyzZIs"
#              valueFrom:
#                secretKeyRef:
#                  name: pickle-rick-investments-conf
#                  key: TELEGRAM_BOT
            - name: GCP_CREDENTIALS_JSON
              valueFrom:
                secretKeyRef:
                  name: pickle-rick-investments-conf
                  key: GCP_CREDENTIALS_JSON
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"