apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcarcoba-com-cert
  namespace: cert-manager
spec:
  secretName: mcarcoba-com-cert-secret
  issuerRef:
    name: letsencrypt-stg
    kind: ClusterIssuer
  dnsNames:
    - mcarcoba.com
