apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcarcoba-com-cert
  namespace: cert-manager
spec:
  secretName: mcarcoba-com-cert-secret
  issuerRef:
    name: cloudflare-prod
    kind: ClusterIssuer
  commonName: mcarcoba.com
  dnsNames:
    - mcarcoba.com
    - grafana.mcarcoba.com
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
