apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: [ "/metadata/annotations/prometheus-operator-validated" ]
        target:
          kind: PrometheusRule
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yaml
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: false

    prometheus:
      prometheusSpec:
        auth:
          prometheusAdminPassword: "1Novatillo6!"
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 10Gi
              storageClassName: "/mcarcoba/backups"
        scrapeInterval: 60s
        retention: 168h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: { }
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
#      ingress:
#        enabled: true
#        ingressClassName: traefik
#        annotations:
#          kubernetes.io/ingress.class: traefik
#          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#          cert-manager.io/cluster-issuer: cloudflare-prod
##          traefik.ingress.kubernetes.io/router.middlewares: "google-oidc-auth@kubernetescrd"
#          traefik.ingress.kubernetes.io/router.tls: "true"
#        hosts:
#          - prometheus.mcarcoba.com
#        paths:
#          - /
#        tls:
#          - secretName: mcarcoba-end-cert
#            hosts:
#              - prometheus.mcarcoba.com
    grafana:
      defaultDashboardsEnabled: false
      adminPassword: "1Novatillo6!"
      assertNoLeakedSecrets: false # TODO remove
      rbac:
        create: true
        serviceAccount:
          create: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: cloudflare-prod
          traefik.ingress.kubernetes.io/router.middlewares: "google-oidc-auth@kubernetescrd"
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - grafana.mcarcoba.com
        paths:
          - /
        tls:
          - secretName: mcarcoba-end-cert
            hosts:
              - grafana.mcarcoba.com
      grafana.ini:
        dashboards:
          default:
            disableDeletion: true
        server:
          domain: grafana.mcarcoba.com
          root_url: "https://grafana.mcarcoba.com/"
          serve_from_sub_path: true
          enable_gzip: true