apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: system
spec:
  releaseName: keycloak
  interval: 5m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: system
      version: "22.0.1"
  values:
    replicaCount: 1
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    persistence:
      enabled: true
      size: 10Gi
    keycloak:
      auth:
        adminUser: admin
        adminPassword: 1Novatillo6!
