apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcarcoba-com-tls
  namespace: default
spec:
  secretName: mcarcoba-com-tls-secret
  dnsNames:
    - mcarcoba.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: mcarcoba.com
