apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: system
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: system
  values:
    auth:
      username: keycloak
      password: 1Novatillo6!
      database: keycloakdb
    primary:
      persistence:
        enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: system
spec:
  interval: 1m
  chart:
    spec:
      chart: keycloak
      version: 24.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: system
  values:
    global:
      postgresql:
        enabled: false
    replicaCount: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "250m"
    persistence:
      enabled: true
      size: 10Gi
    keycloak:
      auth:
        adminUser: admin
        adminPassword: 1Novatillo6!
