apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/cert-manager/cert-manager
  ref:
    branch: release-1.13 # Adjust to the desired version
